### ISSUE TITLE
Any specific reason to build this dashboard for redis broker

### ISSUE THREAD

**Issue by sathk882** [Bogdanp/dramatiq_dashboard#2]
Is there any specific reason to build this dashboard only for redis broker. Because I tried to switch to redis broker so that I will be able to use this dashboard. But it is slow(took more time) compared to RabbitMQ broker.  Any pointers how we can extend this for RabbitMQ broker? I tried to find out why redis is slower than rabbitmq as a broker and found out this [link](https://stackoverflow.com/questions/29539443/redis-vs-rabbitmq-as-a-data-broker-messaging-system-in-between-logstash-and-elas)

**Comment by Bogdanp** [comment]
That’s odd. The Redis broker should be about as fast or faster than the RMQ broker. 

Either way, the reason this dashboard doesn’t support RMQ is because it can’t. AMQP does not provide any reliable way to inspect the state and contents of a queue. To gain access to a message’s contents, you have to remove it from the queue.

If you absolutely need to use RMQ, then I would suggest using its management UI.  You can also leverage the Prometheus support in Dramatiq for monitoring (via something like Grafana).

**Comment by sathk882** [comment]
Ok, Thank you. I will try to find out why redis is slower than rabbitmq in my case. Closing the issue.

**Comment by WillDaSilva** [comment]
@Bogdanp Would it be possible to use the RabbitMQ management plugin (the same one that powers the management UI) to provide a Dramatiq dashboard? I believe that's what Celery Flower does.
